name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1-focal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Running Playwright tests..."
          npm run test:ci
